swagger: '2.0'
info:
  description: A Simple utility to convert CSV files into JSON parent-child tree structure
  title: Create JSON
  version: v1
host: 127.0.0.1:5000
schemes:
  - http
basePath: /
paths:
  /:
    get:
      summary: Welcome page
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              message:
                type: string
                example: Welcome to the Json builder. Upload your CSV file at URL /upload-file
  /upload-file:
    post:
      summary: Upload CSV file to be converted
      consumes:
         - multipart/form-data
      parameters:
         - in: formData
           name: file
           type: file
           description: The CSV file to be converted
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              message:
                type: string
                example: File successfully uploaded. Converted JSON can be found at URL /converted-json
        '400':
          description: Failure response
          schema:
            type: object
            properties:
              message:
                type: string
                example: File missing in the request
  /converted-json:
    get:
      summary: Retrieve the converted JSON text/file
      responses:
        '200':
          description: Success response
        '400':
          description: Failure response
          schema:
            type: object
            properties:
              message:
                type: string
                example: JSON not available. To generate JSON upload CSV at URL /upload-filewagge